// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  echoId: __t.u64().name("echo_id"),
  fromPlace: __t.u8().name("from_place"),
  toPlace: __t.u8().name("to_place"),
  departTs: __t.timestamp().name("depart_ts"),
  arriveTs: __t.timestamp().name("arrive_ts"),
});
