// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  slug: __t.string(),
  name: __t.string(),
  domain: __t.string(),
  hqArea: __t.string().name("hq_area"),
  lng: __t.f64(),
  lat: __t.f64(),
  category: __t.string(),
  logo: __t.string(),
  featured: __t.bool(),
});
