// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  conversationId: __t.u64().name("conversation_id"),
  identity: __t.identity(),
  summary: __t.string(),
  scoresJson: __t.string().name("scores_json"),
  corrective: __t.u8(),
  correctiveNotesJson: __t.string().name("corrective_notes_json"),
  match: __t.u8(),
  createdAt: __t.timestamp().name("created_at"),
});
