// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  echoA: __t.u64().name("echo_a"),
  echoB: __t.u64().name("echo_b"),
  placeId: __t.u8().name("place_id"),
  replies: __t.u8(),
  score: __t.u8(),
  why: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
