// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  provider: __t.string(),
  providerId: __t.string().name("provider_id"),
  handle: __t.string(),
  displayName: __t.string().name("display_name"),
  avatarUrl: __t.string().name("avatar_url"),
  hostedDomain: __t.string().name("hosted_domain"),
  linkedAt: __t.timestamp().name("linked_at"),
});
