// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  avatar: __t.string(),
  online: __t.bool(),
  currentPlace: __t.u8().name("current_place"),
  openrouterLinked: __t.bool().name("openrouter_linked"),
  companyId: __t.u32().name("company_id"),
  verifiedDomain: __t.string().name("verified_domain"),
  joinedAt: __t.timestamp().name("joined_at"),
});
