// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  runOwner: __t.identity().name("run_owner"),
  kind: __t.string(),
  placeId: __t.u8().name("place_id"),
  text: __t.string(),
  costUsd: __t.f64().name("cost_usd"),
  createdAt: __t.timestamp().name("created_at"),
});
