// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  echoId: __t.u64().name("echo_id"),
  goal: __t.string(),
  maxPeople: __t.u8().name("max_people"),
  repliesPerPerson: __t.u8().name("replies_per_person"),
  creditCap: __t.u32().name("credit_cap"),
  allowedActions: __t.string().name("allowed_actions"),
  status: __t.string(),
  startedAt: __t.timestamp().name("started_at"),
  peopleMet: __t.u32().name("people_met"),
  placesVisited: __t.u32().name("places_visited"),
  built: __t.u32(),
  creditsSpent: __t.u32().name("credits_spent"),
});
