// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentTravel = __t.object("AgentTravel", {
  id: __t.u64(),
  echoId: __t.u64(),
  fromPlace: __t.u8(),
  toPlace: __t.u8(),
  departTs: __t.timestamp(),
  arriveTs: __t.timestamp(),
});
export type AgentTravel = __Infer<typeof AgentTravel>;

export const Company = __t.object("Company", {
  id: __t.u32(),
  slug: __t.string(),
  name: __t.string(),
  domain: __t.string(),
  hqArea: __t.string(),
  lng: __t.f64(),
  lat: __t.f64(),
  category: __t.string(),
  logo: __t.string(),
  featured: __t.bool(),
});
export type Company = __Infer<typeof Company>;

export const Contact = __t.object("Contact", {
  identity: __t.identity(),
  email: __t.string(),
  welcomed: __t.bool(),
});
export type Contact = __Infer<typeof Contact>;

export const Conversation = __t.object("Conversation", {
  id: __t.u64(),
  echoA: __t.u64(),
  echoB: __t.u64(),
  placeId: __t.u8(),
  replies: __t.u8(),
  score: __t.u8(),
  why: __t.string(),
  fundingA: __t.string(),
  fundingB: __t.string(),
  createdAt: __t.timestamp(),
});
export type Conversation = __Infer<typeof Conversation>;

export const Correction = __t.object("Correction", {
  id: __t.u64(),
  lineId: __t.u64(),
  owner: __t.identity(),
  originalText: __t.string(),
  shouldHaveSaid: __t.string(),
  behaviourChange: __t.string(),
  appliedAt: __t.timestamp(),
});
export type Correction = __Infer<typeof Correction>;

export const Echo = __t.object("Echo", {
  id: __t.u64(),
  owner: __t.identity(),
  persona: __t.string(),
  behaviourNotes: __t.string(),
  freeUsed: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type Echo = __Infer<typeof Echo>;

export const Intent = __t.object("Intent", {
  id: __t.u64(),
  owner: __t.identity(),
  echoId: __t.u64(),
  text: __t.string(),
  shareId: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type Intent = __Infer<typeof Intent>;

export const LlmConfig = __t.object("LlmConfig", {
  id: __t.u8(),
  owner: __t.identity(),
  apiKey: __t.string(),
  model: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LlmConfig = __Infer<typeof LlmConfig>;

export const Mission = __t.object("Mission", {
  id: __t.u8(),
  text: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Mission = __Infer<typeof Mission>;

export const Place = __t.object("Place", {
  id: __t.u8(),
  name: __t.string(),
  lng: __t.f64(),
  lat: __t.f64(),
});
export type Place = __Infer<typeof Place>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  avatar: __t.string(),
  online: __t.bool(),
  currentPlace: __t.u8(),
  openrouterLinked: __t.bool(),
  companyId: __t.u32(),
  verifiedDomain: __t.string(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerKey = __t.object("PlayerKey", {
  identity: __t.identity(),
  apiKey: __t.string(),
  model: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlayerKey = __Infer<typeof PlayerKey>;

export const Receipt = __t.object("Receipt", {
  id: __t.u64(),
  runOwner: __t.identity(),
  kind: __t.string(),
  placeId: __t.u8(),
  text: __t.string(),
  costUsd: __t.f64(),
  createdAt: __t.timestamp(),
});
export type Receipt = __Infer<typeof Receipt>;

export const Run = __t.object("Run", {
  id: __t.u64(),
  owner: __t.identity(),
  echoId: __t.u64(),
  goal: __t.string(),
  status: __t.string(),
  startedAt: __t.timestamp(),
  peopleMet: __t.u32(),
  placesVisited: __t.u32(),
  spentUsd: __t.f64(),
  hostEchoId: __t.u64(),
  hostMet: __t.bool(),
});
export type Run = __Infer<typeof Run>;

export const Secret = __t.object("Secret", {
  key: __t.string(),
  value: __t.string(),
});
export type Secret = __Infer<typeof Secret>;

export const TalkJob = __t.object("TalkJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  conversationId: __t.u64(),
  payer: __t.identity(),
});
export type TalkJob = __Infer<typeof TalkJob>;

export const TranscriptLine = __t.object("TranscriptLine", {
  id: __t.u64(),
  conversationId: __t.u64(),
  speakerEchoId: __t.u64(),
  text: __t.string(),
  isAi: __t.bool(),
  feedback: __t.string(),
  createdAt: __t.timestamp(),
});
export type TranscriptLine = __Infer<typeof TranscriptLine>;

export const Verification = __t.object("Verification", {
  identity: __t.identity(),
  email: __t.string(),
  domain: __t.string(),
  code: __t.string(),
  expiresAt: __t.timestamp(),
  attempts: __t.u8(),
  sendsThisHour: __t.u8(),
  windowStart: __t.timestamp(),
});
export type Verification = __Infer<typeof Verification>;

export const WorldTick = __t.object("WorldTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldTick = __Infer<typeof WorldTick>;

