// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as SuggestIntentsProcedure from "../suggest_intents_procedure";

export type SuggestIntentsArgs = __Infer<typeof SuggestIntentsProcedure.params>;
export type SuggestIntentsResult = __Infer<typeof SuggestIntentsProcedure.returnType>;

