// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as LinkGoogleProcedure from "../link_google_procedure";
import * as LinkOpenRouterProcedure from "../link_open_router_procedure";
import * as ReadRevealProcedure from "../read_reveal_procedure";
import * as RequestVerificationProcedure from "../request_verification_procedure";
import * as VerifyCodeProcedure from "../verify_code_procedure";

export type LinkGoogleArgs = __Infer<typeof LinkGoogleProcedure.params>;
export type LinkGoogleResult = __Infer<typeof LinkGoogleProcedure.returnType>;
export type LinkOpenRouterArgs = __Infer<typeof LinkOpenRouterProcedure.params>;
export type LinkOpenRouterResult = __Infer<typeof LinkOpenRouterProcedure.returnType>;
export type ReadRevealArgs = __Infer<typeof ReadRevealProcedure.params>;
export type ReadRevealResult = __Infer<typeof ReadRevealProcedure.returnType>;
export type RequestVerificationArgs = __Infer<typeof RequestVerificationProcedure.params>;
export type RequestVerificationResult = __Infer<typeof RequestVerificationProcedure.returnType>;
export type VerifyCodeArgs = __Infer<typeof VerifyCodeProcedure.params>;
export type VerifyCodeResult = __Infer<typeof VerifyCodeProcedure.returnType>;

