// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminUnverifyReducer from "../admin_unverify_reducer";
import CorrectReducer from "../correct_reducer";
import CreateEchoReducer from "../create_echo_reducer";
import EndRunReducer from "../end_run_reducer";
import IngestAgentMemoryReducer from "../ingest_agent_memory_reducer";
import JoinReducer from "../join_reducer";
import JoinEventReducer from "../join_event_reducer";
import LeaveEventReducer from "../leave_event_reducer";
import PauseRunReducer from "../pause_run_reducer";
import RateLineReducer from "../rate_line_reducer";
import ResumeRunReducer from "../resume_run_reducer";
import RevealToReducer from "../reveal_to_reducer";
import SeedCompaniesReducer from "../seed_companies_reducer";
import SeedPlacesReducer from "../seed_places_reducer";
import SetAgentLinkReducer from "../set_agent_link_reducer";
import SetGoogleAuthReducer from "../set_google_auth_reducer";
import SetLlmConfigReducer from "../set_llm_config_reducer";
import SetMissionReducer from "../set_mission_reducer";
import SetRevealReducer from "../set_reveal_reducer";
import SetSecretReducer from "../set_secret_reducer";
import StartRunReducer from "../start_run_reducer";
import TravelReducer from "../travel_reducer";
import UnlinkGoogleReducer from "../unlink_google_reducer";
import UnlinkOpenRouterReducer from "../unlink_open_router_reducer";
import UnverifyReducer from "../unverify_reducer";

export type AdminUnverifyParams = __Infer<typeof AdminUnverifyReducer>;
export type CorrectParams = __Infer<typeof CorrectReducer>;
export type CreateEchoParams = __Infer<typeof CreateEchoReducer>;
export type EndRunParams = __Infer<typeof EndRunReducer>;
export type IngestAgentMemoryParams = __Infer<typeof IngestAgentMemoryReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type JoinEventParams = __Infer<typeof JoinEventReducer>;
export type LeaveEventParams = __Infer<typeof LeaveEventReducer>;
export type PauseRunParams = __Infer<typeof PauseRunReducer>;
export type RateLineParams = __Infer<typeof RateLineReducer>;
export type ResumeRunParams = __Infer<typeof ResumeRunReducer>;
export type RevealToParams = __Infer<typeof RevealToReducer>;
export type SeedCompaniesParams = __Infer<typeof SeedCompaniesReducer>;
export type SeedPlacesParams = __Infer<typeof SeedPlacesReducer>;
export type SetAgentLinkParams = __Infer<typeof SetAgentLinkReducer>;
export type SetGoogleAuthParams = __Infer<typeof SetGoogleAuthReducer>;
export type SetLlmConfigParams = __Infer<typeof SetLlmConfigReducer>;
export type SetMissionParams = __Infer<typeof SetMissionReducer>;
export type SetRevealParams = __Infer<typeof SetRevealReducer>;
export type SetSecretParams = __Infer<typeof SetSecretReducer>;
export type StartRunParams = __Infer<typeof StartRunReducer>;
export type TravelParams = __Infer<typeof TravelReducer>;
export type UnlinkGoogleParams = __Infer<typeof UnlinkGoogleReducer>;
export type UnlinkOpenRouterParams = __Infer<typeof UnlinkOpenRouterReducer>;
export type UnverifyParams = __Infer<typeof UnverifyReducer>;

