// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CorrectReducer from "../correct_reducer";
import CreateEchoReducer from "../create_echo_reducer";
import EndRunReducer from "../end_run_reducer";
import JoinReducer from "../join_reducer";
import PauseRunReducer from "../pause_run_reducer";
import RateLineReducer from "../rate_line_reducer";
import ResumeRunReducer from "../resume_run_reducer";
import SetLlmConfigReducer from "../set_llm_config_reducer";
import SetMissionReducer from "../set_mission_reducer";
import SetSecretReducer from "../set_secret_reducer";
import StartRunReducer from "../start_run_reducer";
import TravelReducer from "../travel_reducer";

export type CorrectParams = __Infer<typeof CorrectReducer>;
export type CreateEchoParams = __Infer<typeof CreateEchoReducer>;
export type EndRunParams = __Infer<typeof EndRunReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type PauseRunParams = __Infer<typeof PauseRunReducer>;
export type RateLineParams = __Infer<typeof RateLineReducer>;
export type ResumeRunParams = __Infer<typeof ResumeRunReducer>;
export type SetLlmConfigParams = __Infer<typeof SetLlmConfigReducer>;
export type SetMissionParams = __Infer<typeof SetMissionReducer>;
export type SetSecretParams = __Infer<typeof SetSecretReducer>;
export type StartRunParams = __Infer<typeof StartRunReducer>;
export type TravelParams = __Infer<typeof TravelReducer>;

